/**
 * Markdown reporter — generates Notion/Confluence-ready .md report
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { AnalysisResult } from '../analyzer/index.js';
import type { Finding } from '../analyzer/rules/rule.interface.js';

export function writeMarkdownReport(
  result: AnalysisResult,
  outputDir: string,
): string {
  mkdirSync(outputDir, { recursive: true });

  const { app, findings, healthScore, graphStats, timestamp } = result;
  const lines: string[] = [];

  // Header
  lines.push('# 🫧 Bubble.io App Audit Report');
  lines.push('');
  lines.push(`> Generated by **bubble-io-dead-code-detector** on ${timestamp.toLocaleDateString()}`);
  lines.push('');

  // App info
  lines.push('## App Information');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| App ID | \`${app.meta.id}\` |`);
  lines.push(`| Version | ${app.meta.version} |`);
  lines.push(`| Last Modified | ${app.meta.lastChange.toLocaleString()} |`);
  lines.push(`| Analysis Duration | ${result.analysisDurationMs}ms |`);
  lines.push('');

  // Health score
  lines.push('## 🏥 App Health Score');
  lines.push('');
  lines.push(`### ${healthScore.emoji} ${healthScore.score}/100 — ${healthScore.label}`);
  lines.push('');
  lines.push('| Category | Issues Found | Total | Penalty |');
  lines.push('|---|---|---|---|');

  const bd = healthScore.breakdown;
  lines.push(`| Dead Workflows | ${bd.deadWorkflows.count} | ${bd.deadWorkflows.total} | -${bd.deadWorkflows.penalty}pts |`);
  lines.push(`| Dead DB Fields | ${bd.deadFields.count} | ${bd.deadFields.total} | -${bd.deadFields.penalty}pts |`);
  lines.push(`| Inactive Plugins | ${bd.deadPlugins.count} | ${bd.deadPlugins.total} | -${bd.deadPlugins.penalty}pts |`);
  lines.push(`| Unused Styles | ${bd.deadStyles.count} | ${bd.deadStyles.total} | -${bd.deadStyles.penalty}pts |`);
  lines.push(`| Unused Option Sets | ${bd.deadOptionSets.count} | ${bd.deadOptionSets.total} | -${bd.deadOptionSets.penalty}pts |`);
  lines.push(`| Complexity Violations | ${bd.complexityViolations.count} | — | -${bd.complexityViolations.penalty}pts |`);
  lines.push(`| Security Issues | ${bd.securityIssues.count} | — | -${bd.securityIssues.penalty}pts |`);
  lines.push('');

  // Graph stats
  lines.push('## 📊 Dependency Graph Statistics');
  lines.push('');
  lines.push(`- **Total Nodes:** ${graphStats.totalNodes}`);
  lines.push(`- **Total Edges:** ${graphStats.totalEdges}`);
  lines.push(`- **Pages:** ${graphStats.byKind?.page ?? 0}`);
  lines.push(`- **Elements:** ${graphStats.byKind?.element ?? 0}`);
  lines.push(`- **Workflows:** ${(graphStats.byKind?.workflow ?? 0) + (graphStats.byKind?.api_workflow ?? 0)}`);
  lines.push(`- **Data Types:** ${graphStats.byKind?.data_type ?? 0}`);
  lines.push(`- **Fields:** ${graphStats.byKind?.field ?? 0}`);
  lines.push(`- **Plugins:** ${graphStats.byKind?.plugin ?? 0}`);
  lines.push('');

  // Findings summary
  lines.push('## 🔍 Findings Summary');
  lines.push('');
  lines.push(`**Total:** ${findings.length} issues — ${healthScore.errorCount} errors, ${healthScore.warningCount} warnings, ${healthScore.infoCount} info`);
  lines.push('');

  if (findings.length === 0) {
    lines.push('> ✅ No issues found! Your app is clean.');
  } else {
    // Group by category
    const grouped = groupByCategory(findings);

    for (const [category, catFindings] of Object.entries(grouped)) {
      lines.push(`### ${categoryEmoji(category)} ${categoryTitle(category)}`);
      lines.push('');
      lines.push('| Severity | Confidence | Issue | Location | Safe to Delete |');
      lines.push('|---|---|---|---|---|');

      for (const f of catFindings) {
        const sev = severityEmoji(f.severity);
        const conf = f.confidence;
        const loc = `${f.location.parentName ? f.location.parentName + ' → ' : ''}${f.location.name}`;
        const safe = f.safeToDelete ? '✅ Yes' : '⚠ No';
        lines.push(`| ${sev} ${f.severity} | ${conf} | ${escapeMarkdown(f.message)} | ${escapeMarkdown(loc)} | ${safe} |`);
      }
      lines.push('');

      // Detailed findings
      lines.push('<details>');
      lines.push(`<summary>View detailed suggestions (${catFindings.length} items)</summary>`);
      lines.push('');
      for (const f of catFindings) {
        lines.push(`**${f.location.name}** — ${f.message}`);
        lines.push(`> 💡 ${f.suggestion}`);
        lines.push('');
      }
      lines.push('</details>');
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [bubble-io-dead-code-detector](https://github.com/alexandrmotologa/bubble-io-dead-code-detector)*');

  const outputPath = join(outputDir, 'audit-report.md');
  writeFileSync(outputPath, lines.join('\n'), 'utf-8');
  return outputPath;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function groupByCategory(findings: Finding[]): Record<string, Finding[]> {
  const result: Record<string, Finding[]> = {};
  for (const f of findings) {
    if (!result[f.category]) result[f.category] = [];
    result[f.category].push(f);
  }
  return result;
}

function categoryEmoji(category: string): string {
  const map: Record<string, string> = {
    'dead-code': '🧹',
    complexity: '📊',
    security: '🔐',
    naming: '📝',
    quality: '⭐',
  };
  return map[category] ?? '🔍';
}

function categoryTitle(category: string): string {
  const map: Record<string, string> = {
    'dead-code': 'Dead Code',
    complexity: 'Complexity Issues',
    security: 'Security Issues',
    naming: 'Naming Convention Issues',
    quality: 'Quality Issues',
  };
  return map[category] ?? category;
}

function severityEmoji(severity: string): string {
  const map: Record<string, string> = { error: '🔴', warning: '🟡', info: '🔵' };
  return map[severity] ?? '⚪';
}

function escapeMarkdown(str: string): string {
  return str.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
